---
# .claude Directory Installation Tasks
- name: Check if .claude directory exists
  stat:
    path: "{{ dotfiles_dir }}/.claude"
  register: claude_dir
  tags: claude

- name: Install .claude directory
  copy:
    src: "{{ dotfiles_dir }}/.claude"
    dest: "{{ ansible_user_dir }}/"
    backup: no
    mode: preserve
    directory_mode: '0755'
  when: claude_dir.stat.exists
  register: claude_files_installed
  tags: claude